/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.javaswing;

/**
 *
 * @author Asus GK
 */
public class radioButton extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(radioButton.class.getName());

    /**
     * Creates new form NewJFrame
     */
    public radioButton() {
        initComponents();
        setTitle("Latihan JButton");
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
        setVisible(true);
    }
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        choice1 = new java.awt.Choice();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        Heading = new javax.swing.JLabel();
        btnEasy = new javax.swing.JRadioButton();
        btnMedium = new javax.swing.JRadioButton();
        btnHard = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(102, 255, 102));

        Heading.setBackground(new java.awt.Color(255, 255, 0));
        Heading.setFont(new java.awt.Font("Inter", 1, 24)); // NOI18N
        Heading.setForeground(new java.awt.Color(0, 0, 0));
        Heading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Heading.setText("Select Difficulty");
        Heading.setAlignmentY(0.0F);
        Heading.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Heading.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        buttonGroup2.add(btnEasy);
        btnEasy.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        btnEasy.setForeground(new java.awt.Color(0, 0, 0));
        btnEasy.setSelected(true);
        btnEasy.setText("Easy");

        buttonGroup2.add(btnMedium);
        btnMedium.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        btnMedium.setForeground(new java.awt.Color(0, 0, 0));
        btnMedium.setText("Medium");

        buttonGroup2.add(btnHard);
        btnHard.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        btnHard.setForeground(new java.awt.Color(0, 0, 0));
        btnHard.setText("Hard");
        btnHard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHardActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Heading, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEasy)
                    .addComponent(btnMedium)
                    .addComponent(btnHard))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(Heading)
                .addGap(34, 34, 34)
                .addComponent(btnEasy)
                .addGap(18, 18, 18)
                .addComponent(btnMedium)
                .addGap(18, 18, 18)
                .addComponent(btnHard)
                .addContainerGap(71, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHardActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHardActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new radioButton().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Heading;
    private javax.swing.JRadioButton btnEasy;
    private javax.swing.JRadioButton btnHard;
    private javax.swing.JRadioButton btnMedium;
    private javax.swing.ButtonGroup buttonGroup2;
    private java.awt.Choice choice1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
