/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import com.mycompany.javaswing.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Asus GK
 */
public class radioButtonExample extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(radioButtonExample.class.getName());

    /**
     * Creates new form NewJFrame
     */
    public radioButtonExample() {
        initComponents();
        setTitle("Latihan JButton");
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
        setVisible(true);
    }
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        Heading = new javax.swing.JLabel();
        rbEasy = new javax.swing.JRadioButton();
        rbMedium = new javax.swing.JRadioButton();
        rbHard = new javax.swing.JRadioButton();
        tampilkanPilihan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(102, 255, 102));

        Heading.setBackground(new java.awt.Color(255, 255, 0));
        Heading.setFont(new java.awt.Font("Inter", 1, 24)); // NOI18N
        Heading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Heading.setText("Select Difficulty");
        Heading.setAlignmentY(0.0F);
        Heading.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Heading.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        buttonGroup1.add(rbEasy);
        rbEasy.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rbEasy.setText("Easy");

        buttonGroup1.add(rbMedium);
        rbMedium.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rbMedium.setText("Medium");
        rbMedium.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbMediumActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbHard);
        rbHard.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rbHard.setText("Hard");

        tampilkanPilihan.setText("Tampilkan Pilihan");
        tampilkanPilihan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tampilkanPilihanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Heading, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tampilkanPilihan)
                            .addComponent(rbMedium)
                            .addComponent(rbEasy))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(rbHard)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(Heading)
                .addGap(34, 34, 34)
                .addComponent(rbEasy)
                .addGap(18, 18, 18)
                .addComponent(rbMedium)
                .addGap(18, 18, 18)
                .addComponent(rbHard)
                .addGap(18, 18, 18)
                .addComponent(tampilkanPilihan)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbMediumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbMediumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbMediumActionPerformed

    private void tampilkanPilihanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tampilkanPilihanActionPerformed
        // TODO add your handling code here:
        String pilihan = "";
        if (rbEasy.isSelected()) {
            pilihan = "Easy";
        } else if (rbMedium.isSelected()) {
            pilihan = "Medium";
        } else if (rbHard.isSelected()) {
            pilihan = "Hard";
        } else {
            pilihan = "Anda belum memilih!";
        }

        JOptionPane.showMessageDialog(this, "Kamu memilih: " + pilihan);
    }//GEN-LAST:event_tampilkanPilihanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new radioButtonExample().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Heading;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton rbEasy;
    private javax.swing.JRadioButton rbHard;
    private javax.swing.JRadioButton rbMedium;
    private javax.swing.JButton tampilkanPilihan;
    // End of variables declaration//GEN-END:variables
}
