/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import javax.swing.JOptionPane;

/**
 *
 * @author Asus GK
 */
public class checkBoxExample extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(radioButtonExample.class.getName());

    /**
     * Creates new form NewJFrame
     */
    public checkBoxExample() {
        initComponents();
        setTitle("Check Box");
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
        setVisible(true);
    }
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        Heading = new javax.swing.JLabel();
        tampilkanPilihan = new javax.swing.JButton();
        cbMobileDev = new javax.swing.JCheckBox();
        cbWebDev = new javax.swing.JCheckBox();
        cbDataAnalyst = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(102, 255, 102));

        Heading.setBackground(new java.awt.Color(255, 255, 0));
        Heading.setFont(new java.awt.Font("Inter", 1, 24)); // NOI18N
        Heading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Heading.setText("Perminatan");
        Heading.setAlignmentY(0.0F);
        Heading.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Heading.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        tampilkanPilihan.setBackground(new java.awt.Color(204, 255, 204));
        tampilkanPilihan.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        tampilkanPilihan.setText("Tampilkan Pilihan");
        tampilkanPilihan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tampilkanPilihanActionPerformed(evt);
            }
        });

        cbMobileDev.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        cbMobileDev.setText("Mobile Developer");
        cbMobileDev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMobileDevActionPerformed(evt);
            }
        });

        cbWebDev.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        cbWebDev.setText("Web Developer");
        cbWebDev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbWebDevActionPerformed(evt);
            }
        });

        cbDataAnalyst.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        cbDataAnalyst.setText("Data Analyst");
        cbDataAnalyst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbDataAnalystActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Heading, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tampilkanPilihan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbWebDev)
                    .addComponent(cbDataAnalyst)
                    .addComponent(cbMobileDev, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(Heading)
                .addGap(46, 46, 46)
                .addComponent(cbMobileDev)
                .addGap(18, 18, 18)
                .addComponent(cbWebDev)
                .addGap(18, 18, 18)
                .addComponent(cbDataAnalyst)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(tampilkanPilihan)
                .addGap(16, 16, 16))
        );

        getContentPane().add(jPanel2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tampilkanPilihanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tampilkanPilihanActionPerformed
        // TODO add your handling code here:
        String hasil;
        java.util.StringJoiner joiner = new java.util.StringJoiner(", ");

        if (cbMobileDev.isSelected()) {
            joiner.add("Mobile Developer");
        }
        if (cbWebDev.isSelected()) {
            joiner.add("Web Developer");
        }
        if (cbDataAnalyst.isSelected()) {
            joiner.add("Data Analyst");
        }

        if (joiner.length() == 0) {
            hasil = "Anda belum memilih perminatan!";
        } else {
            hasil = "Perminatan kamu adalah: " + joiner.toString();
        }

        JOptionPane.showMessageDialog(null, hasil);
    }//GEN-LAST:event_tampilkanPilihanActionPerformed

    private void cbMobileDevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMobileDevActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbMobileDevActionPerformed

    private void cbWebDevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbWebDevActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbWebDevActionPerformed

    private void cbDataAnalystActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbDataAnalystActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbDataAnalystActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new checkBoxExample().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Heading;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox cbDataAnalyst;
    private javax.swing.JCheckBox cbMobileDev;
    private javax.swing.JCheckBox cbWebDev;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton tampilkanPilihan;
    // End of variables declaration//GEN-END:variables
}
